server:
  port: 80

spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/app1?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/app2?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://localhost:3306/app1?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      #username: root
      #password: root
      #driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: jerrylin414@gmail.com
    password: hgne zzqf vjjo yutc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


#mybatis:
#  executor-type: batch
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml

