package com.lzy.pnaWeb.mapper.primary;

import com.lzy.pnaWeb.entity.User1;
import com.lzy.pnaWeb.entity.User1Example;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface User1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    long countByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    int deleteByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    int insert(User1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    int insertSelective(User1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    List<User1> selectByExample(User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    User1 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    int updateByExampleSelective(@Param("row") User1 row, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    int updateByExample(@Param("row") User1 row, @Param("example") User1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    int updateByPrimaryKeySelective(User1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbg.generated Wed Jan 29 19:36:32 GMT+08:00 2025
     */
    int updateByPrimaryKey(User1 row);

    @Select("select * from user1")
    List<User1> findList1();

}