package com.lzy.pnaWeb.mapper.secondary;

import com.lzy.pnaWeb.entity.User2;
import com.lzy.pnaWeb.entity.User2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface User2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    long countByExample(User2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    int deleteByExample(User2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    int insert(User2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    int insertSelective(User2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    List<User2> selectByExample(User2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    User2 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    int updateByExampleSelective(@Param("row") User2 row, @Param("example") User2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    int updateByExample(@Param("row") User2 row, @Param("example") User2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    int updateByPrimaryKeySelective(User2 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbg.generated Wed Jan 29 19:35:51 GMT+08:00 2025
     */
    int updateByPrimaryKey(User2 row);


    @Select("select * from user2")
    List<User2> findList2();
}